### ISSUE TITLE
Can't install the tool via npm 

### ISSUE THREAD

**Issue by xlogix** [ranisalt/node-argon2-cli#25]
Welcome to the issues section if it's your first time!

### Before creating an issue, please be sure to:
- [ x] Checkout to the latest version, **including submodules**
- [ x] Try to find an *isolated* way to reproduce the behavior
- [ x] Fill in all the blanks in the most specific way you can

### Steps to reproduce
1. Run npm i -g argon2-cli
2. An error occurs in arrgon@0.25.1

### Expected behaviour
The package should be installed

### Actual behaviour
An error occurred. 

### Environment
**Operating system**:
MacOS 10.15.4
XCode 11.3.1

**Node version:**
v12.16.1

**Compiler version:**
CXX=g++-6

**Comment by xlogix** [comment]
Upgrading to argon2 v0.26.1 should fix the issue as a similar error occurred while installing v0.25.1

**Comment by xlogix** [comment]
Can confirm that the package installs after updating the dependency

**Comment by ranisalt** [comment]
What are you using this tool for? Out of curiosity. I don't maintain it anymore, but I don't know what are the usages.

**Comment by xlogix** [comment]
Using it to quickly set up passwords for new users on my app.  Also, this CLI helped to quicky test Argon2 and get a feel of it. I'll suggest keeping it up for beginners like me.

**Comment by Yukigamine** [comment]
I ran into the same issue trying to generate a password following the [documentation for code-server](https://github.com/cdr/code-server/blob/main/docs/FAQ.md#can-i-store-my-password-hashed).

From the log, it looks like the main thing that's wrong is it's trying to install argon2@0.25.1 and getting a 404 from github when it tries to pull a release file that no longer exists.

```
npm WARN deprecated node-pre-gyp@0.13.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future

> argon2@0.25.1 install /config/workspace/node_modules/argon2-cli/node_modules/argon2
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/ranisalt/node-argon2/releases/download/v0.25.1/argon2-v0.25.1-node-v83-linux-x64-glibc.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for argon2@0.25.1 and node@14.17.5 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:192:21)
gyp ERR! System Linux 5.4.119-1-pve
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/config/workspace/node_modules/argon2-cli/node_modules/argon2/lib/binding/argon2.node" "--module_name=argon2" "--module_path=/config/workspace/node_modules/argon2-cli/node_modules/argon2/lib/binding" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /config/workspace/node_modules/argon2-cli/node_modules/argon2
gyp ERR! node -v v14.17.5
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/config/workspace/node_modules/argon2-cli/node_modules/argon2/lib/binding/argon2.node --module_name=argon2 --module_path=/config/workspace/node_modules/argon2-cli/node_modules/argon2/lib/binding --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/config/workspace/node_modules/argon2-cli/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Linux 5.4.119-1-pve
node-pre-gyp ERR! command "/usr/bin/node" "/config/workspace/node_modules/argon2-cli/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /config/workspace/node_modules/argon2-cli/node_modules/argon2
node-pre-gyp ERR! node -v v14.17.5
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/config/workspace/node_modules/argon2-cli/node_modules/argon2/lib/binding/argon2.node --module_name=argon2 --module_path=/config/workspace/node_modules/argon2-cli/node_modules/argon2/lib/binding --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm WARN enoent ENOENT: no such file or directory, open '/config/workspace/package.json'
npm WARN workspace No description
npm WARN workspace No repository field.
npm WARN workspace No README data
npm WARN workspace No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon2@0.25.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the argon2@0.25.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /config/.npm/_logs/2021-08-27T20_06_21_282Z-debug.log
```

**Comment by ErixWong** [comment]
I got the similar issue:
`npm ERR! node-pre-gyp http GET https://github.com/ranisalt/node-argon2/releases/download/v0.25.1/argon2-v0.25.1-node-v108-linux-x64-glibc.tar.gz****`
